### ISSUE TITLE
vue前端代码有问题，产品详情一个都出不来

### ISSUE THREAD

**Issue by mebest100** [ZTY18873242003/tongyimall#2]
vue前端代码有问题，产品详情一个都出不来，能认真点吗，这跟你生产环境完全不一样。就算是抄慕课网的课程也用点心好吧

**Comment by ZTY18873242003** [comment]
？？？你自己认真了？基本的前后端分离原理都不知道在这BB？一看就是想抄项目应付课设的三等货色

**Comment by mebest100** [comment]
你他妈public/imgs目录少传了product目录图片，myList的rooter-link的路由跳转也写错了，这才是产品详情出不来的原因，什么垃圾玩意儿？
后端他妈全部用sqlfactory来查询，你mybatis是学到屁眼去了吗！ 还Oppo移动终端部，丢人现眼的垃圾！

**Comment by ZTY18873242003** [comment]
傻逼一个，嘴还臭。不会跑项目issue放垃圾话，素质感人，仓库一个项目没有在这里当键盘侠。笑死！

**Comment by mebest100** [comment]
老子精通linux , python , java, 比你这垃圾强一百倍，就是看你抄慕课网的项目都抄不利索，实在觉得好笑。
接口请求全部把地址写死，不会用proxy吗，白痴！

**Comment by ZTY18873242003** [comment]
哈哈哈，fw抄课设抄到游磊的小米商城去了。精通的话都说得出,真没脑汁.....
